### PR TITLE
Local integration test

### PR DESCRIPTION
**Pull request by markuman**
##### SUMMARY
* Add the ability to run integration tests locally.
* Fix one module task name in integration test

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
None

##### ADDITIONAL INFORMATION

I added one playbook `localhost.yml` in `tests/integration/targets/`.  
Basically it is one playbook with three plays.

1. It starts a proxysql docker container locally.
2. two thinks happen in the 2nd play
    * It installs dependencies in the running container
    * It executes all integration test roles inside the container
3. It stops the container.

You can control different proxysql version and even change the mysql connector using `--extra-vars`  
Defaults are proxysql 2.2.0 and pymysql.

```
ansible-playbook localhost.yml --extra-vars "mysql_connector=mysqlclient PROXYSQL_VERSION=2.0.18"

...

PLAY RECAP **********************************************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
proxysql                   : ok=1424 changed=693  unreachable=0    failed=0    skipped=294  rescued=0    ignored=0 
``` 

**Requirements**

* python docker sdk
* docker daemon

**Advantage**

* It runs 1:1 the same roles like the integration test in github actions, but locally inside a docker container
* Just the setup role is modified, so it is only running, when proxysql is not already presented.

**Disadvantage**

* modifications that need to be tested locally must be build and installed using `ansible-galaxy` first, before apply the playbook
* It's kind of a hack/convention, because the integration tests does not run with `ansible-test integration`

### CODE REVIEW

**Comment by Andersson007** [comment]
@markuman thanks for the PR!
I woke up an hour ago, so a couple of maybe stupid questions:
1. Can't we run CI tests locally with `ansible-test integration task_name --docker ...` now?
2. If this process is better, it should be documented somewhere in detail (say, in README) how to run CI tests this way and how to read logs, shouldn't it?

**Comment by markuman** [comment]
> Can't we run CI tests locally with ansible-test integration task_name --docker ... now?

I'm not sure about how to pass more docker arguments. Because the setup role uses service/systemd to start and enable proxysql. That's not that simple with systemd/pid1 in docker.


```
ansible-test integration test_proxysql_backend_servers --docker ubuntu1804
...
TASK [setup_proxysql : proxysql | config | enable and start proxysql] **********
fatal: [testhost]: FAILED! => {"changed": false, "cmd": "/bin/systemctl", "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
```

the ubuntu2004 won't start at all

```
 ansible-test integration test_proxysql_backend_servers --docker ubuntu2004
Error response from daemon: Container 2c6c042c55af309fd43283a88bb979e8042cc887e120f8f6f7ae78d53acd4395 is not running
ERROR: Command "docker exec -i 2c6c042c55af309fd43283a88bb979e8042cc887e120f8f6f7ae78d53acd4395 /bin/sh" returned exit status 1.
```

> If this process is better, it should be documented somewhere in detail (say, in README) how to run CI tests this way and how to read logs, shouldn't it?

I wouldn't say better :) It's the only way to run it locally as it is.   
It can be an interims solution until the integration test is reworked. Maybe it should also run its tests against a container.  

And yes, some lines of documentation is missing.

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
@markuman thanks for fixing the tests!

**Pull request merged**
