### PR TITLE
Various Doc fixes

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Various Doc fixes

FYI: all the changes were made in accordance to Ansible Doc guidelines, not because I personally don't like dots in short_descriptions:)

##### ISSUE TYPE
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@markuman I think there are errors related CI themselves

**Comment by markuman** [comment]
Oh wow, my python3-apt installation is failing.

**Comment by markuman** [comment]
fixes with #54

**Comment by Andersson007** [comment]
now this is
```
fatal: [testhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "manager": [
                "apt"
            ],
            "strategy": "first"
        }
    },
    "msg": "Could not detect a supported package manager from the following list: ['apt'], or the required Python library is not installed. Check warnings for details."
}
```

**Comment by Andersson007** [comment]
You mentioned in that pr which introduced the changes that it's impossible to run tests locally. I switched to the commit before and run them with
```
ansible-test integration test_proxysql_backend_servers --docker -vvv > ~/test.log
```
and they passed.
Or did I misunderstood anything?

**Comment by Andersson007** [comment]
@markuman if you don't know this way to run them ^ and it works for you now, maybe we could revert https://github.com/ansible-collections/community.proxysql/pull/51 then?

**Comment by markuman** [comment]
> now this is
> 
> ```
> fatal: [testhost]: FAILED! => {
>     "changed": false,
>     "invocation": {
>         "module_args": {
>             "manager": [
>                 "apt"
>             ],
>             "strategy": "first"
>         }
>     },
>     "msg": "Could not detect a supported package manager from the following list: ['apt'], or the required Python library is not installed. Check warnings for details."
> }
> ```

that's the dependency that is installed, `python3-apt`. 
 
Maybe it's because the python env is [changing to 3.8] while ubuntus apt is using python 3.6?

**Comment by markuman** [comment]
> You mentioned in that pr which introduced the changes that it's impossible to run tests locally. I switched to the commit before and run them with
> 
> ```
> ansible-test integration test_proxysql_backend_servers --docker -vvv > ~/test.log
> ```
> 
> and they passed.
> Or did I misunderstood anything?

No, that is failing, because of missing systemd in the test container: https://github.com/ansible-collections/community.proxysql/blob/main/tests/integration/targets/setup_proxysql/tasks/config.yml#L3  
That works on a VM or physicall host, but not in a docker container.

```
$ ansible-test integration test_proxysql_backend_servers --docker
Running test_proxysql_backend_servers integration test role
[WARNING]: running playbook inside collection community.proxysql

PLAY [testhost] ****************************************************************

TASK [Gathering Facts] *********************************************************
ok: [testhost]

TASK [setup_proxysql : proxysql | install | add apt signing key for percona] ***
changed: [testhost]

TASK [setup_proxysql : proxysql | install | add percona repositories] **********
changed: [testhost] => (item=deb http://repo.percona.com/apt bionic main)
changed: [testhost] => (item=deb-src http://repo.percona.com/apt bionic main)

TASK [setup_proxysql : proxysql | install | install proxysql release] **********
changed: [testhost]

TASK [setup_proxysql : proxysql | install | install packages required by proxysql] ***
changed: [testhost]

TASK [setup_proxysql : proxysql | install | install python packages] ***********
changed: [testhost]

TASK [setup_proxysql : proxysql | config | enable and start proxysql] **********
fatal: [testhost]: FAILED! => {"changed": false, "cmd": "/bin/systemctl", "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
testhost                   : ok=6    changed=5    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

NOTICE: To resume at this test target, use the option: --start-at test_proxysql_backend_servers
ERROR: Command "ansible-playbook test_proxysql_backend_servers-2b9rr4yg.yml -i inventory" returned exit status 2.
ERROR: Command "docker exec cc90aeb8760520234b2c97b6a40c2cbbf1c0f105bd91b3aa55b3a8bc233f1e5c /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/community/proxysql LC_ALL=en_US.UTF-8 /usr/bin/python3.6 /root/ansible/bin/ansible-test integration test_proxysql_backend_servers --metadata tests/output/.tmp/metadata-z5k17ci7.json --truncate 213 --redact --color yes --requirements --allow-destructive" returned exit status 1.

```

**Comment by Andersson007** [comment]
> No, that is failing, because of missing systemd in the test container

Really strange because i ran `ansible-test integration test_proxysql_backend_servers --docker` and got
```
TASK [test_proxysql_backend_servers : test_proxysql_backend_servers | teardown | uninstall proxysql] ***
changed: [testhost]

PLAY RECAP *********************************************************************
testhost                   : ok=227  changed=113  unreachable=0    failed=0    skipped=44   rescued=0    ignored=0   
```

**Comment by Andersson007** [comment]
ready for review

**Comment by Andersson007** [comment]
@markuman thanks for reviewing and merging!

**Pull request merged**
